using Distributions 
using Random 
using LinearAlgebra 
using Plots
using StatsPlots
using StaticArrays
using DataFrames
using Printf
using ProgressMeter
using Printf

include(joinpath(@__DIR__, "Structs.jl"))
include(joinpath(@__DIR__, "Common.jl"))
include(joinpath(@__DIR__, "Modified_bridge.jl"))
include(joinpath(@__DIR__, "McmcAlg.jl"))
include(joinpath(@__DIR__, "SDE.jl"))
include(joinpath(@__DIR__, "Single_individual_inference.jl"))
include(joinpath(@__DIR__, "Single_individual_pilot.jl"))
include(joinpath(@__DIR__, "Bootstrap_filter.jl"))